# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/salesforce-data-export-csv',
                'doc_host': 'https://Karthik-bics.github.io',
                'git_url': 'https://github.com/Karthik-bics/salesforce-data-export-csv',
                'lib_path': 'salesforce_data_export_csv'},
  'syms': { 'salesforce_data_export_csv.core': { 'salesforce_data_export_csv.core.foo': ( 'core.html#foo',
                                                                                          'salesforce_data_export_csv/core.py')}}}
